.ALIASES
V_V1            V1(+=VCC -=0 ) CN @BR0101_AD9146.Sine Freq Test(sch_1):INS2832@SOURCE.VDC.Normal(chips)
R_R4            R4(1=N02990 2=VON ) CN @BR0101_AD9146.Sine Freq Test(sch_1):INS3060@ANALOG.R.Normal(chips)
V_V2            V2(+=0 -=VDD ) CN @BR0101_AD9146.Sine Freq Test(sch_1):INS3112@SOURCE.VDC.Normal(chips)
X_U1            U1(1=N02720 2=N02608 VCC=VCC VEE=VDD VOUT=VOP PD=VCC ) CN @BR0101_AD9146.Sine Freq
+Test(sch_1):INS2652@AD8000P.AD8000.Normal(chips)
R_R3            R3(1=0 2=N02990 ) CN @BR0101_AD9146.Sine Freq Test(sch_1):INS3040@ANALOG.R.Normal(chips)
V_V3            V3(+=N02798 -=0 ) CN @BR0101_AD9146.Sine Freq Test(sch_1):INS2812@SOURCE.VDC.Normal(chips)
X_U2            U2(1=N02720 2=N02990 VCC=VCC VEE=VDD VOUT=VON PD=VCC ) CN @BR0101_AD9146.Sine Freq
+Test(sch_1):INS2896@AD8000P.AD8000.Normal(chips)
R_R2            R2(1=N02608 2=VOP ) CN @BR0101_AD9146.Sine Freq Test(sch_1):INS2576@ANALOG.R.Normal(chips)
R_R1            R1(1=0 2=N02608 ) CN @BR0101_AD9146.Sine Freq Test(sch_1):INS2556@ANALOG.R.Normal(chips)
I_I1            I1(+=0 -=N02608 ) CN @BR0101_AD9146.Sine Freq Test(sch_1):INS3276@SOURCE.ISIN.Normal(chips)
I_I2            I2(+=0 -=N02990 ) CN @BR0101_AD9146.Sine Freq Test(sch_1):INS3322@SOURCE.ISIN.Normal(chips)
R_R5            R5(1=N02798 2=N02720 ) CN @BR0101_AD9146.Sine Freq Test(sch_1):INS3775@ANALOG.R.Normal(chips)
_    _(VCC=VCC)
_    _(VDD=VDD)
_    _(Von=VON)
_    _(Vop=VOP)
.ENDALIASES
