######################################################################
##
## Filename: tb_user_logic.udo
## Created on: Mon Aug 07 9:27:30 中国标准时间 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
