######################################################################
##
## Filename: tb_ip_dds.udo
## Created on: Fri Oct 06 10:54:48 中国标准时间 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
